insighti_dart_homepage:
    path:     /
    defaults: { _controller: InsightiDartBundle:Default:index }

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

id_demo_angular:
    path:     /demo
    defaults: { _controller: InsightiDartBundle:Default:demoAngular }
    options: {expose:true}
    requirements:
        _method: POST